import type { PixelGrid } from "../types";
import { createEmptyGrid, TRANSPARENT } from "../types";

export interface ParsedScene {
  grid: PixelGrid;
  width: number;
  height: number;
  shapeCount: number;
}

function rgbToHex(r: number, g: number, b: number): string {
  const clamp = (n: number) => Math.max(0, Math.min(255, n));
  return `#${[r, g, b].map((n) => clamp(n).toString(16).padStart(2, "0")).join("")}`;
}

function extractField(block: string, name: string): number | null {
  const m = new RegExp(`\\b${name}\\s*:\\s*(-?\\d+(?:\\.\\d+)?)`).exec(block);
  return m ? Number(m[1]) : null;
}

function extractColor(block: string): string | null {
  const rgbMatch = /colors\.rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/.exec(block);
  if (rgbMatch) {
    return rgbToHex(Number(rgbMatch[1]), Number(rgbMatch[2]), Number(rgbMatch[3]));
  }
  const hexMatch = /["']?(#[0-9a-fA-F]{6})["']?/.exec(block);
  if (hexMatch) return hexMatch[1]!.toLowerCase();
  return null;
}

/**
 * Parses code generated by codeGen.ts (`new Point({...})` / `new Rectangle({...})`
 * calls inside a `scene.add(...)` block) back into a pixel grid.
 */
export function parseGeneratedCode(code: string): ParsedScene | null {
  const shapeRe = /new\s+(Point|Rectangle)\s*\(\s*\{([\s\S]*?)\}\s*\)/g;
  const shapes: Array<{ x: number; y: number; width: number; height: number; color: string }> = [];

  let match: RegExpExecArray | null;
  while ((match = shapeRe.exec(code)) !== null) {
    const [, kind, block] = match;
    const x = extractField(block!, "x");
    const y = extractField(block!, "y");
    const color = extractColor(block!);
    if (x === null || y === null || color === null) continue;

    if (kind === "Point") {
      shapes.push({ x, y, width: 1, height: 1, color });
    } else {
      const width = extractField(block!, "width") ?? 1;
      const height = extractField(block!, "height") ?? 1;
      shapes.push({ x, y, width, height, color });
    }
  }

  if (shapes.length === 0) return null;

  let maxX = 0;
  let maxY = 0;
  for (const s of shapes) {
    maxX = Math.max(maxX, s.x + s.width);
    maxY = Math.max(maxY, s.y + s.height);
  }

  const width = Math.max(1, maxX);
  const height = Math.max(1, maxY);
  const grid = createEmptyGrid(width, height);

  for (const s of shapes) {
    for (let dy = 0; dy < s.height; dy++) {
      for (let dx = 0; dx < s.width; dx++) {
        const px = s.x + dx;
        const py = s.y + dy;
        if (px >= 0 && px < width && py >= 0 && py < height) {
          grid[py]![px] = s.color;
        }
      }
    }
  }

  return { grid, width, height, shapeCount: shapes.length };
}

export const MAX_IMAGE_DIMENSION = 256;

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace("#", ""), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

/** Reads the color of one pixel as a lowercase hex string (ignores alpha). */
export function getPixelHex(imageData: ImageData, x: number, y: number): string {
  const i = (y * imageData.width + x) * 4;
  const data = imageData.data;
  return rgbToHex(data[i]!, data[i + 1]!, data[i + 2]!);
}

export interface BackgroundKey {
  color: string;
  /** Max per-channel difference (0-255) still considered a match. */
  tolerance: number;
}

function isBackgroundPixel(
  r: number,
  g: number,
  b: number,
  a: number,
  key: [number, number, number] | null,
  tolerance: number,
): boolean {
  if (a < 32) return true;
  if (!key) return false;
  return (
    Math.abs(r - key[0]) <= tolerance &&
    Math.abs(g - key[1]) <= tolerance &&
    Math.abs(b - key[2]) <= tolerance
  );
}

/**
 * Converts decoded ImageData into a pixel grid. Pixels below the alpha
 * threshold are always transparent; if `bgKey` is given, pixels whose color
 * is within `tolerance` of `bgKey.color` on every channel are also made
 * transparent (a simple chroma-key for flat-color backgrounds).
 */
export function imageDataToGrid(imageData: ImageData, bgKey?: BackgroundKey | null): PixelGrid {
  const { width, height, data } = imageData;
  const grid = createEmptyGrid(width, height);
  const key = bgKey ? hexToRgb(bgKey.color) : null;
  const tolerance = bgKey?.tolerance ?? 0;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      const r = data[i]!;
      const g = data[i + 1]!;
      const b = data[i + 2]!;
      const a = data[i + 3]!;
      grid[y]![x] = isBackgroundPixel(r, g, b, a, key, tolerance) ? TRANSPARENT : rgbToHex(r, g, b);
    }
  }
  return grid;
}

/**
 * Clones `imageData` with the alpha channel zeroed out for background
 * pixels (per the same rule as `imageDataToGrid`), for previewing the
 * chroma-key effect on a canvas before committing the import.
 */
export function previewImageData(imageData: ImageData, bgKey?: BackgroundKey | null): ImageData {
  const { width, height, data } = imageData;
  const out = new ImageData(new Uint8ClampedArray(data), width, height);
  const key = bgKey ? hexToRgb(bgKey.color) : null;
  const tolerance = bgKey?.tolerance ?? 0;

  for (let i = 0; i < out.data.length; i += 4) {
    const r = out.data[i]!;
    const g = out.data[i + 1]!;
    const b = out.data[i + 2]!;
    const a = out.data[i + 3]!;
    if (isBackgroundPixel(r, g, b, a, key, tolerance)) {
      out.data[i + 3] = 0;
    }
  }
  return out;
}

/**
 * Loads an image file into an offscreen canvas and returns its ImageData,
 * downscaling if it exceeds MAX_IMAGE_DIMENSION on either axis.
 */
export function loadImageFile(file: File): Promise<{ imageData: ImageData; scaled: boolean }> {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      URL.revokeObjectURL(url);
      const scale = Math.min(1, MAX_IMAGE_DIMENSION / Math.max(img.width, img.height));
      const width = Math.max(1, Math.round(img.width * scale));
      const height = Math.max(1, Math.round(img.height * scale));

      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        reject(new Error("Canvas 2D context unavailable"));
        return;
      }
      ctx.imageSmoothingEnabled = false;
      ctx.drawImage(img, 0, 0, width, height);
      resolve({ imageData: ctx.getImageData(0, 0, width, height), scaled: scale < 1 });
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error("Failed to load image"));
    };
    img.src = url;
  });
}
